CREATE TABLE IF NOT EXISTS customers(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(25) NOT NULL,
	last_name VARCHAR(25) NOT NULL,
	state CHAR(2) NOT NULL DEFAULT "SP",
	birth_date DATE NOT NULL,
	sex ENUM('M', 'F') NOT NULL,
	money_owed FLOAT NULL,
	last_meeting TIMESTAMP
)ENGINE=MyISAM;

